---
- hosts: 172.31.13.83
  become: Yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: copy my index file into ansible node side
    copy:
      src: myindexfile
      dest: /var/www/html/index.html
  - name: copy index file into ansible node side
    tenmplate:
      src: myindex.j2
      dest: /var/www/html/index.html