---
- hosts: mywebserverslist
  become: Yes
  tasks:
  - name: i want to install java on ubuntu
    apt:
     name: "{{myjavapackageonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to install java into redhat
    dnf:
      name: "{{myjavapackageonredhat}}"
      state: present
    when: ansible_os_family=="RedHat" 