---
- hosts: mywebserverslist
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family== {{mywebpackonubuntu}}
  - name: i want to install webserver on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family== {{mywebpackonubuntu}} 
  - name: i wanto to install webser into redhat
    dnf:
     name: httpd
     state: present
    when: ansible_os_family== {{mywebpackonredhat}}  
  - name: i wanto to start webser into redhat
    service:
     name: httpd
     state: started
    when: ansible_os_family== {{mywebpackonredhat}}  
